on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Prepare
        run: tzutil /s "China Standard Time"
        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load Cache
        uses: actions/cache@v2
        with: 
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        
      - name: Build
        run: |
          python -m pip install wheel setuptools
          python -m pip install -r requirements.txt
          python version.py
          C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pyinstaller --noconfirm --version-file version-file.txt --add-data="icon.ico;." -i icon.ico -F -w -n UpdaterHotupdatePackage main.py
          dir

      - name: Print Hashes
        run: |
          python version.py
          echo "Print Hashes for dist\UpdaterHotupdatePackage.exe"
          echo MD5:
          python .github\tools\sha1.py dist\UpdaterHotupdatePackage.exe
          echo SHA1:
          python .github\tools\md5.py dist\UpdaterHotupdatePackage.exe
      
      - name: Upload To Github Release
        uses: updater-for-minecraft/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: dist/*
          draft: false
          tags: true        
